apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "project-sea-server.fullname" . }}
  labels:
    {{- include "project-sea-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - project-bmrt.ip-ddns.com
      secretName: letsencrypt-prod
  rules:
  - host: project-bmrt.ip-ddns.com
    http:
        paths:
          - backend:
              service:
                name: {{ include "project-sea-server.fullname" . }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
