apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "project-sea-server.fullname" . }}
  labels:
    {{- include "project-sea-server.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - project-bmrt.ip-ddns.com
      secretName: letsencrypt-prod
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "project-sea-server.fullname" . }}
                port:
                  number: 80
