apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-sea-server.fullname" . }}
  labels:
    {{- include "project-sea-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
  selector:
    {{- include "project-sea-server.selectorLabels" . | nindent 4 }}
